# ==============================================================================
# Generated by qmake (2.01a) (Qt 4.6.0) on: zo 6. dec 00:28:02 2009
# This file is generated by qmake and should not be modified by the
# user.
#  Name        : Makefile_0xE5A258F1.mk
#  Part of     : asuroqt
#  Description : This file is used to call necessary targets on wrapper makefile
#                during normal Symbian build process.
#  Version     : 
#
# ==============================================================================



MAKE = make

VISUAL_CFG = RELEASE
ifeq "$(CFG)" "UDEB"
VISUAL_CFG = DEBUG
endif

do_nothing :
	@rem do_nothing

MAKMAKE: create_temps pre_targetdeps store_build

LIB: create_temps pre_targetdeps store_build

BLD: create_temps pre_targetdeps store_build

ifeq "$(PLATFORM)" "WINSCW"
CLEAN: extension_clean winscw_deployment_clean
else
CLEAN: extension_clean
endif

CLEANLIB: do_nothing

RESOURCE: do_nothing

FREEZE: do_nothing

SAVESPACE: do_nothing

RELEASABLES: do_nothing

ifeq "$(PLATFORM)" "WINSCW"
FINAL: finalize winscw_deployment
else
FINAL: finalize
endif

pre_targetdeps : e:\asuro\Carbide-Projects\asuroqt\Makefile
	-$(MAKE) -f "e:\asuro\Carbide-Projects\asuroqt\Makefile" pre_targetdeps QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

create_temps : e:\asuro\Carbide-Projects\asuroqt\Makefile
	-$(MAKE) -f "e:\asuro\Carbide-Projects\asuroqt\Makefile" create_temps QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

extension_clean : e:\asuro\Carbide-Projects\asuroqt\Makefile
	-$(MAKE) -f "e:\asuro\Carbide-Projects\asuroqt\Makefile" extension_clean QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

finalize : e:\asuro\Carbide-Projects\asuroqt\Makefile
	-$(MAKE) -f "e:\asuro\Carbide-Projects\asuroqt\Makefile" finalize QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

winscw_deployment_clean : e:\asuro\Carbide-Projects\asuroqt\Makefile
	-$(MAKE) -f "e:\asuro\Carbide-Projects\asuroqt\Makefile" winscw_deployment_clean QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

winscw_deployment : e:\asuro\Carbide-Projects\asuroqt\Makefile
	-$(MAKE) -f "e:\asuro\Carbide-Projects\asuroqt\Makefile" winscw_deployment QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

store_build : e:\asuro\Carbide-Projects\asuroqt\Makefile
	-$(MAKE) -f "e:\asuro\Carbide-Projects\asuroqt\Makefile" store_build QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)


